name: Run PySide6 Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pip install PySide6 and dependencies 
        run: |
          python3.10 -m pip install PySide6 nose2 nosepipe six packaging setuptools wheel

      - name: Set entrypoint.sh script permissions
        run: |
          chmod +x ./entrypoint.sh

      - name: Run tests from entrypoint.sh
        run: |
          PYTHON=3.10 ./entrypoint.sh
