name: Run PySide6 Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pip install PySide6 and dependencies 
        run: |
          python3.10 -m pip install PySide6 nose2 nosepipe six packaging setuptools wheel

      - name: Testing implementation..
        run: |
          python3.10 -u run_tests.py

      - name: Building caveats..
        run: |
          python3.10 -u build_caveats.py

      - name: Testing caveats..
        run: |
          python3.10 -m nose2 --verbose test_caveats

      - name: Testing examples..
        run: |
          cd examples
          python3.10 -m nose2 --verbose loadUi.baseinstance1
          python3.10 -m nose2 --verbose loadUi.baseinstance2
          python3.10 -m nose2 --verbose QtSiteConfig.main
          cd ..
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}:$(pwd)
